{% set name = "plum-dispatch" %}
{% set version = "2.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plum_dispatch-{{ version }}.tar.gz
  sha256: 38f04f42f2cc4f726083244e52ee04cfd155f53fad55423ec0fd1bfee3fc97a9

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.10
    - hatch-vcs >=0.3
  run:
    - python >={{ python_min }}
    - beartype >=0.12
    - rich >=10.0

test:
  imports:
    - plum
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wesselb/plum
  summary: Multiple dispatch in Python
  license: MIT
  license_file: LICENCE.txt
  doc_url: https://wesselb.github.io/plum
  dev_url: https://github.com/wesselb/plum

extra:
  recipe-maintainers:
    - PhilipVinc
    - wesselb
