{% set name = "plum-dispatch" %}
{% set version = "1.5.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plum-dispatch-{{ version }}.tar.gz
  sha256: 6f406ce1e032b46f04791b806b1923e5ab20a7234c1999441aa10c0b3a9ba7ce

build:
  number: 0
  skip: true  # [py2k]
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython >=0.29
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml
  run:
    - python

test:
  imports:
    - plum
    - tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wesselb/plum
  summary: Multiple dispatch in Python
  license: MIT
  license_file: LICENCE.txt

extra:
  recipe-maintainers:
    - PhilipVinc
    - wesselb
