{% set name = "plum-dispatch" %}
{% set version = "2.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plum_dispatch-{{ version }}.tar.gz
  sha256: d5d180225c9fbf0277375bb558b649d97d0b651a91037bb7155cedbe9f52764b

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.10
    - hatch-vcs >=0.3
  run:
    - python >=3.7
    - beartype >=0.12

test:
  imports:
    - plum
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wesselb/plum
  summary: Multiple dispatch in Python
  license: MIT
  license_file: LICENCE.txt
  doc_url: https://wesselb.github.io/plum
  dev_url: https://github.com/wesselb/plum

extra:
  recipe-maintainers:
    - PhilipVinc
    - wesselb
