{% set name = "plum-dispatch" %}
{% set version = "1.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plum-dispatch-{{ version }}.tar.gz
  sha256: e7639bbffef7995aa801d136935c9f74573db0e0f5dd7bcec83c71de2222f8ad

build:
  number: 0
  skip: true  # [py2k]
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml
  run:
    - python

test:
  imports:
    - plum
    - tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wesselb/plum
  summary: Multiple dispatch in Python
  license: MIT
  license_file: LICENCE.txt

extra:
  recipe-maintainers:
    - PhilipVinc
    - wesselb
