{% set name = "plum-dispatch" %}
{% set version = "2.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plum_dispatch-{{ version }}.tar.gz
  sha256: 9befcb1e98b5c73974950b6e9db233296b2ae10d6907adc1b6774da9ec78ecf7

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.10
    - hatch-vcs >=0.3
  run:
    - python >=3.8
    - beartype >=0.12
    - rich >=10.0

test:
  imports:
    - plum
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wesselb/plum
  summary: Multiple dispatch in Python
  license: MIT
  license_file: LICENCE.txt
  doc_url: https://wesselb.github.io/plum
  dev_url: https://github.com/wesselb/plum

extra:
  recipe-maintainers:
    - PhilipVinc
    - wesselb
