{% set name = "plum-dispatch" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plum-dispatch-{{ version }}.tar.gz
  sha256: 37245135dcd37c8e9eaabcfdb72423ef9d1431ec77b93191f4fe8f0b751acd61

build:
  number:
  skip: true  # [py2k]
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  build:
    - python # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml
  run:
    - python
    - beartype >=0.12

test:
  imports:
    - plum
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wesselb/plum
  summary: Multiple dispatch in Python
  license: MIT
  license_file: LICENCE.txt
  doc_url: https://wesselb.github.io/plum
  dev_url: https://github.com/wesselb/plum
  
extra:
  recipe-maintainers:
    - PhilipVinc
    - wesselb
