{% set name = "plum-dispatch" %}
{% set version = "1.5.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plum-dispatch-{{ version }}.tar.gz
  sha256: ec52f17bc8756b70ffb0fcc06838f90f6a82c2490c4ef7d73bccc68e80864f48

build:
  number: 0
  skip: true  # [py2k]
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython >=0.29
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml
  run:
    - python

test:
  imports:
    - plum
    - tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wesselb/plum
  summary: Multiple dispatch in Python
  license: MIT
  license_file: LICENCE.txt

extra:
  recipe-maintainers:
    - PhilipVinc
    - wesselb
