{% set name = "plum-dispatch" %}
{% set version = "2.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plum_dispatch-{{ version }}.tar.gz
  sha256: 69a0b80f55c35cda4066384cc60942c85945a80685d6e22fab8f14601ebe3b76

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.10
    - hatch-vcs >=0.3
  run:
    - python >=3.8
    - beartype >=0.12
    - rich >=10.0

test:
  imports:
    - plum
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wesselb/plum
  summary: Multiple dispatch in Python
  license: MIT
  license_file: LICENCE.txt
  doc_url: https://wesselb.github.io/plum
  dev_url: https://github.com/wesselb/plum

extra:
  recipe-maintainers:
    - PhilipVinc
    - wesselb
